import { SUPPORTED_LANGUAGE_COUNT } from '../languages/registry.js';
import {
  buildExtractorRoutingMermaid,
  buildLanguageFamiliesMermaid,
  buildLanguagePipelineMermaid,
} from '../languages/docs.js';
import { buildMemoryPipelineMermaid } from '../graph/mermaid.js';

const GENERATED_BANNER = `<!-- Auto-generated by Mnemos — run \`npm run docs:sync\` to refresh -->`;

/** Static `docs/GRAPHS.md` — catalog of every Mermaid diagram type Mnemos produces. */
export function buildGraphsReferenceMarkdown(): string {
  return `${GENERATED_BANNER}

# Mnemos Architecture Graphs

Mnemos embeds **Mermaid diagrams** in markdown everywhere architecture matters — repo docs, \`.mnemos/context/\`, \`AGENTS.md\`, MCP resources, and the dashboard.

## Where graphs appear

| Location | Generated | Contents |
|----------|-----------|----------|
| [\`docs/GRAPHS.md\`](./GRAPHS.md) | \`npm run docs:sync\` | This catalog (static) |
| [\`docs/LANGUAGES.md\`](./LANGUAGES.md) | \`npm run docs:sync\` | ${SUPPORTED_LANGUAGE_COUNT}-language pipeline + families |
| [\`docs/architecture.md\`](./architecture.md) | Hand-maintained + sync sections | System pipeline |
| \`.mnemos/context/graphs.md\` | \`mnemos build\` | **Per-repo** domain, flow, dependency, risk charts |
| \`.mnemos/context/languages.md\` | \`mnemos build\` | **Per-repo** language pie + parsing pipeline |
| \`.mnemos/context/architecture.md\` | \`mnemos build\` | Layers + services + language section |
| \`.mnemos/context/domains.md\` | \`mnemos build\` | Domain interaction graph |
| \`.mnemos/context/flows.md\` | \`mnemos build\` | Flow overview + step diagrams |
| \`.mnemos/context/dependencies.md\` | \`mnemos build\` | Top edges + service graph |
| \`.mnemos/context/critical_paths.md\` | \`mnemos build\` | High-risk path diagram |
| \`.mnemos/context/smells.md\` | \`mnemos build\` | Smell severity pie |
| \`AGENTS.md\` | \`mnemos setup\` | Domain graph + language pipeline |

## End-to-end build pipeline

${buildMemoryPipelineMermaid()}

## Language parsing pipeline (${SUPPORTED_LANGUAGE_COUNT} languages)

${buildLanguagePipelineMermaid()}

## Extractor routing

${buildExtractorRoutingMermaid()}

## Language families

${buildLanguageFamiliesMermaid()}

## Per-repository diagram types

After \`npx mnemos .\`, open \`.mnemos/context/graphs.md\` for repo-specific charts:

| Diagram | Source data | Markdown section |
|---------|-------------|------------------|
| Architecture layers | \`architecture.layers\` | \`graphs.md\` · \`architecture.md\` |
| Domain map | Import + call clustering | \`graphs.md\` · \`domains.md\` |
| Flow overview | Execution flows | \`graphs.md\` · \`flows.md\` |
| Service dependencies | Service graph | \`graphs.md\` · \`dependencies.md\` |
| Top dependency edges | Weighted IMPORTS | \`dependencies.md\` |
| Critical paths | Blast-radius paths | \`critical_paths.md\` |
| Capabilities map | Product features | \`graphs.md\` |
| User journeys | Journey systems | \`graphs.md\` |
| Language pie | File counts by language | \`languages.md\` · \`graphs.md\` |
| Risk heatmap | Domain risk scores | \`graphs.md\` |
| Smell severity | Architecture smells | \`smells.md\` |

## Rendering tips

- **GitHub / GitLab** — Mermaid renders natively in \`.md\` files
- **Cursor / VS Code** — Markdown preview with Mermaid extension
- **Agents** — Point at \`.mnemos/context/graphs.md\` before editing cross-cutting code

## Implementation

| Module | Role |
|--------|------|
| \`packages/core/src/graph/mermaid.ts\` | Domain, flow, service, risk diagrams |
| \`packages/core/src/languages/docs.ts\` | Language pipeline + pie charts |
| \`packages/core/src/context/graph-markdown.ts\` | Composes \`.mnemos/context/graphs.md\` |
| \`packages/core/src/context/compiler.ts\` | Writes all \`context/*.md\` at build time |
`;
}

/** Architecture doc body with graphs for \`docs/architecture.md\` sync. */
export function buildArchitectureReferenceMarkdown(): string {
  return `# Mnemos Architecture

Mnemos transforms a codebase into structured intelligence through a local-first pipeline.

${GENERATED_BANNER}

## System pipeline

${buildMemoryPipelineMermaid()}

## Scanner

Walks the repository filesystem (respecting \`.gitignore\`), detects **${SUPPORTED_LANGUAGE_COUNT} languages**, and feeds files through the lexical parsing pipeline. Output: parsed imports, symbols, calls, and file nodes.

${buildLanguagePipelineMermaid()}

See **[LANGUAGES.md](./LANGUAGES.md)** for the full language list, families mindmap, and extractor routing.

## Analyzer

Runs on the in-memory graph:

- **Domains** — business boundaries from directory structure and imports
- **Capabilities** — product features inferred from routes, handlers, and naming
- **Journeys** — user-facing flows from entry points to outcomes
- **Flows** — execution paths through the call graph
- **Smells** — architecture anti-patterns (god modules, circular deps, etc.)
- **Heatmap** — per-domain risk scoring
- **AI readiness** — six dimensions for agent-friendliness

\`\`\`mermaid
flowchart LR
  GRAPH[Knowledge graph] --> DOM[Domains]
  GRAPH --> CAP[Capabilities]
  GRAPH --> JRN[Journeys]
  GRAPH --> FLOW[Flows]
  GRAPH --> SMELL[Smells]
  GRAPH --> HEAT[Risk heatmap]
  DOM --> MEM[memory.json]
  CAP --> MEM
  JRN --> MEM
  FLOW --> MEM
  SMELL --> MEM
  HEAT --> MEM
\`\`\`

## Memory

Written to \`.mnemos/\` after \`mnemos build\`:

| File | Purpose |
|------|---------|
| \`memory.json\` | Full memory model |
| \`project.dna.json\` | Compressed DNA (~few KB) — read this first |
| \`agent_context.json\` | Machine-optimized bundle |
| \`graph.json\` | Dependency graph for visualization |
| \`health-score.json\` | Five-dimension health score |
| \`context/*.md\` | Human-readable docs with **Mermaid graphs** |

### Context markdown index

| File | Graphs included |
|------|-----------------|
| [\`graphs.md\`](./GRAPHS.md) | Master index — all diagram types |
| \`languages.md\` | Language pie + pipeline + routing |
| \`architecture.md\` | Layers, domain overview, capabilities |
| \`domains.md\` | Domain interaction graph |
| \`flows.md\` | Flow overview + per-flow steps |
| \`dependencies.md\` | Top edges + service dependency graph |
| \`critical_paths.md\` | Critical path diagram |
| \`smells.md\` | Smell severity pie |
| \`repository_summary.md\` | Layers + language pie + domain snapshot |

Run \`npx mnemos .\` on any repo to generate the full set under \`.mnemos/context/\`.

## Outputs

All outputs call the same **\`buildAiPack\`** builder in \`packages/core/src/ai-pack.ts\`:

1. **Dashboard** — React Router v7 app with Vibe / AI / Coder cockpits
2. **Report** — static HTML from \`report-template.ts\`
3. **AI Pack v1** — JSON via CLI, serve, and \`/api/json/:repoId\`
4. **MCP + REST** — \`MnemosRuntime\` shared by \`mnemos serve\` and \`mnemos mcp\`

## Packages

| Package | Role |
|---------|------|
| \`@mnestis/core\` | Scanner, analyzer, memory, AI Pack, report, serve, MCP |
| \`@mnestis/cli\` | \`mnemos\` command-line interface |
| \`@mnestis/ui\` | Vite + React dashboard |

## Design principles

- **Local-first** — no telemetry, no cloud, no required API keys
- **Single source of truth** — one AI Pack builder, one runtime
- **Modes are routes** — \`/vibe/…\`, \`/ai/…\`, \`/coder/…\`
- **Graphs in markdown** — every context doc ships Mermaid for humans and agents

## Related docs

- [GRAPHS.md](./GRAPHS.md) — full diagram catalog
- [LANGUAGES.md](./LANGUAGES.md) — ${SUPPORTED_LANGUAGE_COUNT}-language parsing reference
- [modes.md](./modes.md) — Vibe / AI / Coder routes
- [ai-pack.md](./ai-pack.md) — AI Pack v1 specification
`;
}
