import type { MemoryModel } from './types.js';
import { computeDomainHeatmap } from './analysis/heatmap.js';
import {
  buildCriticalPathGraphBody,
  buildDomainGraphBody,
  buildFlowGraphBody,
  buildServiceDependencyGraphBody,
} from './graph/mermaid.js';

export interface CallflowOptions {
  outputPath?: string;
}

export function generateCallflowHtml(memory: MemoryModel): string {
  const heatmap = computeDomainHeatmap(memory);
  const topRisk = [...heatmap].sort((a, b) => b.riskScore - a.riskScore).slice(0, 5);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${memory.repository} — Architecture Call Flow</title>
  <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: system-ui, -apple-system, sans-serif; background: #0d1117; color: #e6edf3; padding: 2rem; line-height: 1.6; }
    h1 { font-size: 1.75rem; margin-bottom: 0.5rem; }
    h2 { font-size: 1.25rem; margin: 2rem 0 1rem; color: #58a6ff; }
    .subtitle { color: #8b949e; margin-bottom: 2rem; }
    .card { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1.5rem; margin-bottom: 1.5rem; }
    .mermaid { background: #0d1117; padding: 1rem; border-radius: 6px; overflow-x: auto; }
    .risk-high { color: #f85149; }
    .risk-med { color: #d29922; }
    .risk-low { color: #3fb950; }
    ul { padding-left: 1.25rem; }
    li { margin: 0.25rem 0; }
    .meta { display: flex; gap: 2rem; flex-wrap: wrap; margin-bottom: 1rem; }
    .meta span { color: #8b949e; }
    .meta strong { color: #e6edf3; }
  </style>
</head>
<body>
  <h1>${memory.repository}</h1>
  <p class="subtitle">Architecture call-flow visualization — generated by Mnemos</p>

  <div class="meta">
    <span>Architecture: <strong>${memory.architecture.type}</strong></span>
    <span>Domains: <strong>${memory.domains.length}</strong></span>
    <span>Flows: <strong>${memory.flows.length}</strong></span>
    <span>Services: <strong>${memory.services.length}</strong></span>
  </div>

  <div class="card">
    <h2>Domain Interactions</h2>
    <pre class="mermaid">${buildDomainGraphBody(memory)}</pre>
  </div>

  <div class="card">
    <h2>Top Execution Flow</h2>
    <pre class="mermaid">${buildFlowGraphBody(memory, 0)}</pre>
    <p style="margin-top:1rem;color:#8b949e">${memory.flows[0]?.description ?? ''}</p>
  </div>

  <div class="card">
    <h2>Critical Paths</h2>
    <pre class="mermaid">${buildCriticalPathGraphBody(memory)}</pre>
    <ul style="margin-top:1rem">
      ${memory.criticalPaths
        .slice(0, 5)
        .map(
          (cp: { risk: string; name: string; description: string }) =>
            `<li><span class="risk-${cp.risk === 'high' ? 'high' : cp.risk === 'medium' ? 'med' : 'low'}">${cp.risk.toUpperCase()}</span> — <strong>${cp.name}</strong>: ${cp.description}</li>`,
        )
        .join('\n')}
    </ul>
  </div>

  <div class="card">
    <h2>Service Dependencies</h2>
    <pre class="mermaid">${buildServiceDependencyGraphBody(memory)}</pre>
  </div>

  <div class="card">
    <h2>Risk Heatmap</h2>
    <ul>
      ${topRisk
        .map((h) => `<li><strong>${h.domain}</strong> — risk ${h.riskScore}/100 (${h.problems.join(', ') || 'stable'})</li>`)
        .join('\n')}
    </ul>
  </div>

  <script>mermaid.initialize({ startOnLoad: true, theme: 'dark' });</script>
</body>
</html>`;
}

export async function writeCallflowHtml(
  memory: MemoryModel,
  outputDir: string,
): Promise<string> {
  const { writeFile, mkdir } = await import('node:fs/promises');
  const path = await import('node:path');
  await mkdir(outputDir, { recursive: true });
  const outPath = path.join(outputDir, 'callflow.html');
  await writeFile(outPath, generateCallflowHtml(memory), 'utf-8');
  return outPath;
}

export {
  buildDomainGraphBody as buildDomainDiagram,
  buildFlowGraphBody as buildFlowDiagram,
  buildCriticalPathGraphBody as buildCriticalPathDiagram,
  buildServiceDependencyGraphBody as buildServiceDiagram,
} from './graph/mermaid.js';
