import type { MemoryModel } from '../types.js';
import type { MnemosGraph } from '../graph/graph.js';
import { toSerializable } from '../graph/graph.js';
import { buildDomainGraphMermaid, buildFlowGraphMermaid, buildServiceDependencyGraphMermaid } from '../graph/mermaid.js';
import { buildRepositoryLanguagePieMermaid } from '../languages/docs.js';

function escapeXml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export function exportGraphSvg(graph: MnemosGraph, memory: MemoryModel): string {
  const { nodes, edges } = toSerializable(graph);
  const displayNodes = nodes.slice(0, 80);
  const nodeIds = new Set(displayNodes.map((n) => n.id));

  const cols = Math.ceil(Math.sqrt(displayNodes.length));
  const cellW = 140;
  const cellH = 60;
  const width = cols * cellW + 40;
  const rows = Math.ceil(displayNodes.length / cols);
  const height = rows * cellH + 80;

  const positions = new Map<string, { x: number; y: number }>();
  displayNodes.forEach((n, i) => {
    const col = i % cols;
    const row = Math.floor(i / cols);
    positions.set(n.id, { x: 20 + col * cellW + cellW / 2, y: 40 + row * cellH + cellH / 2 });
  });

  const edgeLines = edges
    .filter((e) => nodeIds.has(e.source) && nodeIds.has(e.target))
    .slice(0, 120)
    .map((e) => {
      const from = positions.get(e.source);
      const to = positions.get(e.target);
      if (!from || !to) return '';
      return `<line x1="${from.x}" y1="${from.y}" x2="${to.x}" y2="${to.y}" stroke="#6366f1" stroke-width="1" opacity="0.5"/>`;
    })
    .join('\n');

  const nodeEls = displayNodes
    .map((n) => {
      const pos = positions.get(n.id)!;
      const label = n.name.length > 14 ? n.name.slice(0, 12) + '…' : n.name;
      return `<g>
  <rect x="${pos.x - 50}" y="${pos.y - 18}" width="100" height="36" rx="6" fill="#1e1b4b" stroke="#6366f1"/>
  <text x="${pos.x}" y="${pos.y + 4}" text-anchor="middle" fill="#e0e7ff" font-size="11" font-family="system-ui,sans-serif">${escapeXml(label)}</text>
</g>`;
    })
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">
  <rect width="100%" height="100%" fill="#0f172a"/>
  <text x="20" y="24" fill="#94a3b8" font-size="14" font-family="system-ui,sans-serif">${escapeXml(memory.repository)} — Knowledge Graph (${displayNodes.length} nodes)</text>
  ${edgeLines}
  ${nodeEls}
</svg>`;
}

export function exportGraphml(graph: MnemosGraph, memory: MemoryModel): string {
  const { nodes, edges } = toSerializable(graph);

  const nodeXml = nodes
    .map(
      (n) => `    <node id="${escapeXml(n.id)}">
      <data key="label">${escapeXml(n.name)}</data>
      <data key="kind">${escapeXml(n.kind)}</data>
      ${n.path ? `<data key="path">${escapeXml(n.path)}</data>` : ''}
    </node>`,
    )
    .join('\n');

  const edgeXml = edges
    .map(
      (e) =>
        `    <edge source="${escapeXml(e.source)}" target="${escapeXml(e.target)}"><data key="kind">${escapeXml(e.kind)}</data></edge>`,
    )
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns">
  <key id="label" for="node" attr.name="label" attr.type="string"/>
  <key id="kind" for="all" attr.name="kind" attr.type="string"/>
  <key id="path" for="node" attr.name="path" attr.type="string"/>
  <graph id="${escapeXml(memory.repository)}" edgedefault="directed">
${nodeXml}
${edgeXml}
  </graph>
</graphml>`;
}

export function exportWiki(memory: MemoryModel): Map<string, string> {
  const pages = new Map<string, string>();

  const indexLines = [
    `# ${memory.repository} — Architecture Wiki`,
    '',
    `> Generated by Mnemos`,
    '',
    `**Architecture:** ${memory.architecture.type}`,
    '',
    '## Domain map',
    '',
    buildDomainGraphMermaid(memory),
    '',
    '## Languages',
    '',
    buildRepositoryLanguagePieMermaid(memory.architecture.languages ?? {}),
    '',
    '## Domains',
    '',
    ...memory.domains.map((d) => `- [${d.name}](domains/${slugify(d.name)}.md) — ${d.description || 'core domain'}`),
    '',
    '## Flows',
    '',
    ...memory.flows.slice(0, 20).map((f) => `- [${f.name}](flows/${slugify(f.name)}.md)`),
    '',
    '## Services',
    '',
    ...memory.services.slice(0, 30).map((s) => `- [${s.name}](services/${slugify(s.name)}.md)`),
  ];
  pages.set('index.md', indexLines.join('\n'));

  for (const d of memory.domains) {
    const slug = slugify(d.name);
    pages.set(
      `domains/${slug}.md`,
      [
        `# Domain: ${d.name}`,
        '',
        d.description,
        '',
        `**Confidence:** ${(d.confidence * 100).toFixed(0)}%`,
        `**Nodes:** ${d.nodes.length}`,
        '',
        buildDomainGraphMermaid(memory),
        '',
        '## Entry points',
        ...d.entryPoints.slice(0, 15).map((e) => `- \`${e}\``),
        '',
        '## Related services',
        ...memory.services
          .filter((s) => s.domain === d.id || s.domain === d.name)
          .slice(0, 10)
          .map((s) => `- [${s.name}](../services/${slugify(s.name)}.md)`),
      ].join('\n'),
    );
  }

  for (const [fi, f] of memory.flows.slice(0, 30).entries()) {
    pages.set(
      `flows/${slugify(f.name)}.md`,
      [
        `# Flow: ${f.name}`,
        '',
        f.description,
        '',
        `**Type:** ${f.type}`,
        `**Entry:** ${f.entryPoint}`,
        '',
        buildFlowGraphMermaid(memory, fi),
        '',
        '## Steps',
        ...f.steps.map((s, i) => `${i + 1}. **${s.name}**${s.path ? ` — \`${s.path}\`` : ''}`),
      ].join('\n'),
    );
  }

  for (const s of memory.services.slice(0, 50)) {
    pages.set(
      `services/${slugify(s.name)}.md`,
      [
        `# Service: ${s.name}`,
        '',
        `**Path:** \`${s.path}\``,
        s.domain ? `**Domain:** ${s.domain}` : '',
        '',
        buildServiceDependencyGraphMermaid(memory),
        '',
        '## Dependencies',
        ...(s.dependencies.length ? s.dependencies.map((d) => `- ${d}`) : ['- none']),
        '',
        '## Dependents',
        ...(s.dependents.length ? s.dependents.map((d) => `- ${d}`) : ['- none']),
      ]
        .filter(Boolean)
        .join('\n'),
    );
  }

  return pages;
}

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

export type ExportFormat = 'svg' | 'graphml' | 'callflow' | 'wiki' | 'vault';

export async function runExport(
  format: ExportFormat,
  memory: MemoryModel,
  outputDir: string,
  graph?: MnemosGraph,
): Promise<string | string[]> {
  const { writeFile, mkdir } = await import('node:fs/promises');
  const path = await import('node:path');

  switch (format) {
    case 'svg': {
      if (!graph) throw new Error('Graph required for SVG export. Run mnestis build first.');
      const out = path.join(outputDir, 'graph.svg');
      await writeFile(out, exportGraphSvg(graph, memory), 'utf-8');
      return out;
    }
    case 'graphml': {
      if (!graph) throw new Error('Graph required for GraphML export.');
      const out = path.join(outputDir, 'graph.graphml');
      await writeFile(out, exportGraphml(graph, memory), 'utf-8');
      return out;
    }
    case 'callflow': {
      const { writeCallflowHtml } = await import('../callflow.js');
      return writeCallflowHtml(memory, outputDir);
    }
    case 'wiki': {
      const wikiDir = path.join(outputDir, 'wiki');
      const pages = exportWiki(memory);
      for (const [rel, content] of pages) {
        const full = path.join(wikiDir, rel);
        await mkdir(path.dirname(full), { recursive: true });
        await writeFile(full, content, 'utf-8');
      }
      return wikiDir;
    }
    case 'vault': {
      const { exportObsidianVault } = await import('../vault/obsidian.js');
      const result = await exportObsidianVault(memory, outputDir);
      return result.vaultDir;
    }
    default:
      throw new Error(`Unknown export format: ${format}`);
  }
}
