import type { MemoryModel } from '../types.js';
import {
  buildAllFlowsOverviewMermaid,
  buildArchitectureLayersMermaid,
  buildCapabilitiesGraphMermaid,
  buildCriticalPathGraphMermaid,
  buildDomainGraphMermaid,
  buildFlowGraphMermaid,
  buildGraphIndexSections,
  buildJourneyGraphMermaid,
  buildMemoryPipelineMermaid,
  buildRiskHeatmapMermaid,
  buildServiceDependencyGraphMermaid,
  buildSmellsSeverityMermaid,
  buildTopDependenciesMermaid,
} from '../graph/mermaid.js';
import {
  buildLanguagePipelineMermaid,
  buildRepositoryLanguagePieMermaid,
  buildExtractorRoutingMermaid,
  buildLanguageFamiliesMermaid,
} from '../languages/docs.js';
import { SUPPORTED_LANGUAGE_COUNT } from '../languages/registry.js';

/** Master graphs index — `.mnemos/context/graphs.md` */
export function buildGraphsIndexMarkdown(memory: MemoryModel): string {
  const sections = buildGraphIndexSections(memory);
  const { architecture } = memory;

  return `# Architecture Graphs — ${architecture.name}

> Mermaid diagrams generated by Mnemos at build time. Render in GitHub, Cursor, VS Code, or any Mermaid-capable viewer.

## System layers

${sections.overview}

## Domain map

Cross-domain dependency edges inferred from imports and call graph.

${sections.domains}

## Execution flows

${sections.flows}

### Top flow detail

${memory.flows[0] ? `**${memory.flows[0].name}** — ${memory.flows[0].description}\n\n${sections.topFlow}` : '_No flows detected._'}

## Service dependencies

${sections.services}

## Key dependency edges

${sections.dependencies}

## Critical paths

${sections.criticalPaths}

## Capabilities

${sections.capabilities}

## User journeys

${sections.journeys}

## Language distribution

${buildRepositoryLanguagePieMermaid(architecture.languages ?? {})}

## Language families (engine)

${buildLanguageFamiliesMermaid()}

## Parsing pipeline (${architecture.languages ? Object.keys(architecture.languages).length : 0} detected · ${SUPPORTED_LANGUAGE_COUNT} supported)

${buildLanguagePipelineMermaid()}

## Extractor routing

${buildExtractorRoutingMermaid()}

## Risk heatmap

${sections.risk}

## Architecture smells

${sections.smells}

## Mnemos build pipeline

${sections.pipeline}

## Related docs

| File | Contents |
|------|----------|
| [architecture.md](./architecture.md) | Layers, services, language section |
| [domains.md](./domains.md) | Domain list + domain graph |
| [flows.md](./flows.md) | All flows + step diagrams |
| [dependencies.md](./dependencies.md) | Top edges + service graph |
| [critical_paths.md](./critical_paths.md) | High-risk edit zones |
| [languages.md](./languages.md) | Full language charts |
`;
}

export function buildDomainSectionGraph(memory: MemoryModel): string {
  return `## Domain interaction graph

${buildDomainGraphMermaid(memory)}
`;
}

export function buildFlowsSectionGraphs(memory: MemoryModel): string {
  const parts = [
    '## Flow overview',
    '',
    buildAllFlowsOverviewMermaid(memory),
    '',
  ];

  for (const [i, flow] of memory.flows.slice(0, 5).entries()) {
    parts.push(`### ${flow.name}`, '', flow.description, '', buildFlowGraphMermaid(memory, i), '');
  }

  return parts.join('\n');
}

export function buildDependenciesSectionGraphs(memory: MemoryModel): string {
  return `## Dependency graph (top edges)

${buildTopDependenciesMermaid(memory)}

## Service dependency graph

${buildServiceDependencyGraphMermaid(memory)}
`;
}

export function buildCriticalPathsSectionGraph(memory: MemoryModel): string {
  return `## Critical path diagram

${buildCriticalPathGraphMermaid(memory)}
`;
}

export function buildArchitectureOverviewGraphs(memory: MemoryModel): string {
  return `## Architecture layers

${buildArchitectureLayersMermaid(memory)}

## Domain overview

${buildDomainGraphMermaid(memory)}

## Capabilities map

${buildCapabilitiesGraphMermaid(memory)}
`;
}

export function buildRepositorySummaryGraphs(memory: MemoryModel): string {
  return `## At a glance

${buildArchitectureLayersMermaid(memory)}

## Languages in this repo

${buildRepositoryLanguagePieMermaid(memory.architecture.languages ?? {})}

## Top domains

${buildDomainGraphMermaid(memory)}

See **[graphs.md](./graphs.md)** for the full diagram set.
`;
}

export function buildSmellsSectionGraph(memory: MemoryModel): string {
  return `## Smells by severity

${buildSmellsSeverityMermaid(memory)}
`;
}

export function buildHealthGraphBundle(memory: MemoryModel): string {
  return [
    buildRiskHeatmapMermaid(memory),
    '',
    buildSmellsSeverityMermaid(memory),
    '',
    buildDomainGraphMermaid(memory),
  ].join('\n');
}

export function buildMcpArchitectureGraphBundle(memory: MemoryModel): string {
  const sections = buildGraphIndexSections(memory);
  return [
    '## Architecture graphs',
    '',
    sections.overview,
    '',
    sections.domains,
    '',
    sections.services,
    '',
    buildRepositoryLanguagePieMermaid(memory.architecture.languages ?? {}),
  ].join('\n');
}

export {
  buildGraphIndexSections,
  buildMemoryPipelineMermaid,
  buildDomainGraphMermaid,
  buildFlowGraphMermaid,
  buildJourneyGraphMermaid,
};
